import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync,spawnSync} from 'node:child_process';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';
const script=n=>fileURLToPath(new URL(`../scripts/${n}`,import.meta.url));
test('classifier routes fulfillment separately from payment',()=>{const out=JSON.parse(execFileSync(process.execPath,[script('classify-order-issue.mjs'),'fulfillmentOrder has wrong location and remaining quantity'],{encoding:'utf8'}));assert.equal(out.matches[0].id,'fulfillment-and-shipping')});
test('classifier routes refund and return',()=>{const out=JSON.parse(execFileSync(process.execPath,[script('classify-order-issue.mjs'),'returnCalculate refund tax and restock mismatch'],{encoding:'utf8'}));assert.equal(out.matches[0].id,'returns-refunds-cancellations')});
test('community evidence has 25 to 50 cases with unique exact topic URLs',()=>{const doc=JSON.parse(fs.readFileSync(new URL('../knowledge/community-cases.json',import.meta.url)));assert.ok(doc.cases.length>=25&&doc.cases.length<=50);assert.equal(new Set(doc.cases.map(x=>x.id)).size,doc.cases.length);const urls=doc.cases.map(x=>x.source_url);assert.equal(new Set(urls).size,doc.cases.length);assert.ok(doc.cases.every(x=>x.category&&x.symptom&&/^https:\/\/community\.shopify\.dev\/t\/[a-z0-9-]+\/\d+$/.test(x.source_url)))});
test('snapshot comparator reports lifecycle changes',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orders-'));const a=path.join(dir,'a.json'),b=path.join(dir,'b.json');fs.writeFileSync(a,JSON.stringify({order:{id:'gid://shopify/Order/1',displayFinancialStatus:'AUTHORIZED'}}));fs.writeFileSync(b,JSON.stringify({order:{id:'gid://shopify/Order/1',displayFinancialStatus:'PAID'}}));const out=JSON.parse(execFileSync(process.execPath,[script('compare-order-snapshots.mjs'),a,b],{encoding:'utf8'}));assert.equal(out.sameOrder,true);assert.equal(out.changes.financial.after,'PAID')});
test('webhook analyzer detects duplicate and event reordering',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orders-')),file=path.join(dir,'events.jsonl');fs.writeFileSync(file,[{webhookId:'2',topic:'orders/paid',eventTime:'2025-01-02T00:00:00Z'},{webhookId:'1',topic:'orders/create',eventTime:'2025-01-01T00:00:00Z'},{webhookId:'2',topic:'orders/paid',eventTime:'2025-01-02T00:00:00Z'}].map(JSON.stringify).join('\n'));const out=JSON.parse(execFileSync(process.execPath,[script('analyze-webhook-log.mjs'),file],{encoding:'utf8'}));assert.deepEqual(out.duplicateWebhookIds,['2']);assert.equal(out.eventOrderChanged,true)});
test('runner blocks mutation before resolving credentials',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orders-')),file=path.join(dir,'mutation.graphql');fs.writeFileSync(file,'mutation X { orderClose(input: {id: "gid://shopify/Order/1"}) { userErrors { message } } }');const out=spawnSync(process.execPath,[script('run-order-query.mjs'),'--query',file],{encoding:'utf8'});assert.equal(out.status,3);assert.match(out.stderr,/Mutation blocked/)});
test('runner blocks mutation hidden after a read operation',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orders-')),file=path.join(dir,'mixed.graphql');fs.writeFileSync(file,'query Read { shop { name } }\nmutation Write { orderClose(input: {id: "gid://shopify/Order/1"}) { userErrors { message } } }');const out=spawnSync(process.execPath,[script('run-order-query.mjs'),'--query',file],{encoding:'utf8'});assert.equal(out.status,3)});
