import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const run=(script,args=[])=>spawnSync(process.execPath,[fileURLToPath(new URL(`../scripts/${script}`,import.meta.url)),...args],{encoding:'utf8'});
test('classifier deterministically ranks variant issue',()=>{const r=run('classify-product-issue.mjs',['productVariantsBulk duplicate option variant']);assert.equal(r.status,0);const x=JSON.parse(r.stdout);assert.equal(x.matches[0].id,'variants-options');assert.ok(x.matches[0].score>=3);});
test('classifier reports unclassified input',()=>{const r=run('classify-product-issue.mjs',['unrelated symptom']);assert.equal(r.status,1);assert.equal(JSON.parse(r.stdout).unclassified,true);});
test('summarizer captures GraphQL and nested user errors without token fields',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'product-skill-'));const f=path.join(dir,'r.json');fs.writeFileSync(f,JSON.stringify({data:{productUpdate:{userErrors:[{field:['product','title'],code:'INVALID',message:'bad'}]}},errors:[{message:'denied',extensions:{code:'ACCESS_DENIED'}}],extensions:{cost:{requestedQueryCost:10,actualQueryCost:2,throttleStatus:{currentlyAvailable:998}}},accessToken:'secret'}));const r=run('summarize-product-response.mjs',[f]);assert.equal(r.status,1);const x=JSON.parse(r.stdout);assert.equal(x.userErrors.length,1);assert.equal(x.graphqlErrors[0].code,'ACCESS_DENIED');assert.equal(r.stdout.includes('secret'),false);});
test('comparison ignores shop-local GIDs but detects stable changes',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'product-compare-'));const a=path.join(dir,'a.json'),b=path.join(dir,'b.json');fs.writeFileSync(a,JSON.stringify({product:{id:'gid://shopify/Product/1',handle:'shoe',title:'Shoe',status:'ACTIVE',variants:[{id:'1',sku:'S-1',title:'Blue'}]}}));fs.writeFileSync(b,JSON.stringify({product:{id:'gid://shopify/Product/9',handle:'shoe',title:'Shoe',status:'ACTIVE',variants:[{id:'9',sku:'S-1',title:'Blue'}]}}));assert.equal(run('compare-products.mjs',[a,b]).status,0);const changed=JSON.parse(fs.readFileSync(b));changed.product.status='DRAFT';fs.writeFileSync(b,JSON.stringify(changed));const r=run('compare-products.mjs',[a,b]);assert.equal(r.status,1);assert.equal(JSON.parse(r.stdout).differences[0].field,'status');});
test('knowledge contains 25-50 distinct traceable Community topics',()=>{const lines=fs.readFileSync(new URL('../knowledge/community-cases.jsonl',import.meta.url),'utf8').trim().split('\n').map(JSON.parse);assert.ok(lines.length>=25&&lines.length<=50);assert.equal(new Set(lines.map(x=>x.id)).size,lines.length);assert.equal(new Set(lines.map(x=>x.url)).size,lines.length);for(const x of lines){assert.match(x.url,/^https:\/\/community\.shopify\.dev\/t\/.+\/\d+$/);assert.match(x['official-url'],/^https:\/\/shopify\.dev\//);assert.ok(x.symptom&&x.pattern);}});
test('every routed pattern exists',()=>{const index=JSON.parse(fs.readFileSync(new URL('../patterns/index.json',import.meta.url)));for(const x of index.routing)assert.equal(fs.existsSync(new URL(`../patterns/${x.pattern}`,import.meta.url)),true);});
test('query runner blocks mutation before credentials',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'product-query-'));const f=path.join(dir,'mutation.graphql');fs.writeFileSync(f,'mutation { productDelete(input: {id: "gid://shopify/Product/1"}) { deletedProductId } }');const r=run('run-product-query.mjs',['--query',f]);assert.equal(r.status,3);assert.match(r.stderr,/Mutation blocked/);});
