import test from 'node:test'; import assert from 'node:assert/strict'; import {execFileSync,spawnSync} from 'node:child_process'; import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os';
const root=path.resolve('datadog/diagnose-datadog');
test('router selects traces',()=>{const x=JSON.parse(execFileSync('node',[`${root}/scripts/classify-issue.mjs`,'missing trace span'],{encoding:'utf8'}));assert.equal(x.id,'traces-apm')});
test('every route file exists',()=>{const i=JSON.parse(fs.readFileSync(`${root}/patterns/index.json`));for(const r of i.routes) assert.ok(fs.existsSync(`${root}/patterns/${r.file}`))});
test('context resolves and strips auth',()=>{const out=JSON.parse(execFileSync('node',[`${root}/scripts/resolve-context.mjs`,'--env','qa','--service','example-api'],{encoding:'utf8',env:{...process.env,DATADOG_DIAGNOSTICS_CONFIG:path.resolve('datadog/shared/config/datadog-config.example.json')}}));assert.equal(out.org,'example-nonprod');assert.equal(out.service.name,'example-api');assert.equal(out.auth,undefined)});
test('ambiguous environment fails',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dd-'));const f=path.join(dir,'x.json');fs.writeFileSync(f,JSON.stringify({'configs-envs-mapping':[{'config-name':'a',envs:['qa']},{'config-name':'b',envs:['qa']}],configs:[]}));assert.throws(()=>execFileSync('node',[`${root}/scripts/resolve-context.mjs`,'--env','qa','--config',f],{stdio:'pipe'}))});
test('validator permits bounded GET',()=>{const p=spawnSync('node',[`${root}/scripts/validate-plan.mjs`],{input:'GET logs from=now-15m limit=100',encoding:'utf8'});assert.equal(p.status,0)});
test('validator blocks mutation',()=>{const p=spawnSync('node',[`${root}/scripts/validate-plan.mjs`],{input:'DELETE monitor 1',encoding:'utf8'});assert.equal(p.status,1)});
test('redactor removes keys and identifiers',()=>{const out=execFileSync('node',[`${root}/scripts/redact-evidence.mjs`],{input:JSON.stringify({api_key:'x',email:'a@b.com',message:'Bearer abc.def'}),encoding:'utf8'});assert.ok(!out.includes('a@b.com'));assert.ok(!out.includes('abc.def'))});
